apiVersion: v1
kind: Service
metadata:
  name: dummy-backend-service
  namespace: development
  labels:
    app: dummy-backend-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: dummy-backend-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-backend-service
  namespace: development
  labels:
    app:dummy-backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-backend-service
  template:
    metadata:
      labels:
        app: dummy-backend-service
    spec:
      containers:
      - name: dummy-backend-service
        image: razvan95/dummy-backend-service:1.0
        ports:
        - containerPort: 8080