apiVersion: v1
kind: Service
metadata:
  name: dummy-frontend-service
  namespace: development
  labels:
    app: dummy-frontend-service
spec:
  type: NodePort
  ports:
  - port: 4200
    targetPort: 4200
    nodePort: 30030
    protocol: TCP
  selector:
    app: dummy-frontend-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-frontend-service
  namespace: development
  labels:
    app: dummy-frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-frontend-service
  template:
    metadata:
      labels:
        app: dummy-frontend-service
    spec:
      containers:
      - name: dummy-frontend-service
        image: razvan95/dummy-frontend-service:1.0
        resources:
            requests:
                memory: "128Mi"
                cpu: "250m"
            limits:
                memory: "256Mi"
                cpu: "500m"
        ports:
        - containerPort: 4200