apiVersion: v1
kind: Namespace
metadata:
  name: nexus
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    app: nexus
spec:
  capacity:
    storage: 5Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: 192.168.1.106 # Please change this to your NFS server
    path: /srv/nfs4/data/nexus # Please change this to the relevant share

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  accessModes:
    - ReadWriteMany # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 5Gi # volume size requested

---

apiVersion: v1
kind: Service
metadata: 
  name: nexus-service
  namespace: nexus
  labels: 
    app: nexus
spec: 
  type: NodePort   
  ports: 
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector: 
    app: nexus
    
--- 
      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus:latest
          securityContext:
            runAsUser: 0
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chown -R 200:200 /opt/nexus"]
          env:
          - name: MAX_HEAP
            value: "800m"
          - name: MIN_HEAP
            value: "300m"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /sonatype-work
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pv-claim